config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pics
  
  root "pics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :pics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_action :find_pic, only: [:show, :edit, :update, :destroy]

	def index
		@pics = Pic.all.order("created_at DESC")
	end

	def show
	end

	def new
		@pic = current_user.pics.build
	end

	def create
		@pic = current_user.pics.build(pics_params)

		if @pic.save
			redirect_to @pic, notice: "Yessss! It was posted!"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pic.update(pics_params)
			redirect_to @pic, notice: "Congrats! Pic was updated"
		else
			render 'edit'
		end
	end

	def destroy
		@pic.destroy
		redirect_to root_path
	end

	private
		def pics_params
			params.require(:pic).permit(:title, :description)
		end

		def find_pic
			@pic = Pic.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title Instagramm
		= csrf_meta_tags
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

	%body
		%nav.navbar.navbar-inverse
			.container
				.navbar-brand= link_to "Instagramm", root_path

				- if user_signed_in?
					%ul.nav.navbar-nav.navbar-left
						%li= link_to "Gram It!", new_pic_path
						%li= link_to "Setting", edit_user_registration_path
						%li= link_to "Sign Out", destroy_user_session_path, method: :delete

				- else
					%ul.nav.navbar-nav.navbar-left
						%li= link_to "Join", new_user_registration_path
						%li= link_to "Log In", new_user_session_path

		.container
			-flash.each do |name, msg|
				= content_tag :div, msg, class: "alert alert-info"

			= yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true } do |f|
	- if @pic.errors.any?
		#errors
			%h2
			= pluralize(@pic.errors.count, "error")
			prevent this Pic from saving
			%ul
				- @pic.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :title, input_html: { class: 'form-control' }
	.form-group
		= f.input :description, input_html: { class: 'form-control'}

	= f.button :submit, class: "btn btn-info"

app/views/pics/edit.html.haml
%h1 Fix Pic!

= render 'form'

= link_to "Cancel", pic_path

app/views/pics/index.html.haml
- @pics.each do |pic|
	%h2= link_to pic.title, pic

= link_to "Gram It", new_pic_path

app/views/pics/new.html.haml
%h1 Post Pic

= render 'form'

= link_to "Back", root_path

app/views/pics/show.html.haml
%h1= @pic.title
%p= @pic.description
%p
Pic by
= @pic.user.email

%br
= link_to "Back", root_path
= link_to "Edit", edit_pic_path(@pic)
= link_to "Delete", pic_path, method: :delete, data: { confirm: "Are you sure?" }